services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    network_mode: host

  app:
    build: .
    container_name: telegram_bot
    restart: always
    network_mode: host
    volumes:
      - .:/app
